
---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: haifa54
    password: Besthaf123456haha

- name: Tag and push to docker hub
  docker_image:
    name: angular:latest
    repository: haifa54/myapp
    tag: end
    push: yes

#
#- name: Push to docker hub
#  docker_image:
#    name: "haifa54/myapp"
#    repository: haifa54/myapp
#    push: yes

